version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:5000
    env_file:
      - .env
    volumes:
      - .:/web_djangoAPI
    ports:
      - '5000:5000'
    depends_on:
      - db
  db:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: 'db_django'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'

    volumes:
      - ./db_django:/var/lib/mysql/
    restart: always