# Generated by Django 3.2.8 on 2021-11-30 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20211130_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ('-created_at',), 'verbose_name': 'Example table', 'verbose_name_plural': 'Example table'},
        ),
        migrations.AlterModelTable(
            name='tutorial',
            table='tutorial',
        ),
    ]
