# Generated by Django 3.2.8 on 2021-12-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_parser', '0003_auto_20211221_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.TextField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
