# Generated by Django 3.2.8 on 2022-01-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_parser', '0007_alter_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='room_number',
            field=models.TextField(blank=True, max_length=15, null=True, verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Ссылка на объявление'),
        ),
    ]
