# Generated by Django 3.2.8 on 2022-01-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_parser', '0010_alter_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание объявления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='room_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок объявления'),
        ),
    ]
