# Generated by Django 3.2.8 on 2022-01-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_parser', '0011_auto_20220110_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published_date',
            field=models.TextField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
